name: C++ CI

on: 
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install C++
      run: |
        sudo npx setup-cpp --compiler llvm --cmake true --ninja true --ccache true --vcpkg true
        source ~/.cpprc # activate cpp environment variables

    

    - name: Install dependencies
      run: |
        sudo apt-get install -y g++ make
        sudo apt-get install -y libgtest-dev
    - name: Build
      run: |
        mkdir build
        g++ -o test_sort src/sort.c  src/test_sort.cpp -lgtest -lgtest_main -pthread
        mv test_sort build/

    - name: Run tests
      run: |
        cd build
        ./test_sort # Замените на имя вашего исполняемого файла для тестов
