name: C++ CI

on: 
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install C++
      run: |
      sudo npx setup-cpp --compiler llvm --cmake true --ninja true --ccache true --vcpkg true
      source ~/.cpprc # activate cpp environment variables

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1
      with:
        gcc-version: '12.3.0'  # Замените на нужную версию GCC
        gpp-version: '12.3.0'   # Замените на нужную версию G++

    - name: Install dependencies
      run: sudo apt-get install -y g++ make

    - name: Build
      run: |
        mkdir build
        g++ -o test_sort src/sort.c  src/test_sort.cpp -lgtest -lgtest_main -pthread
        mv test_sort build/

    - name: Run tests
      run: |
        cd build
        ./test_sort # Замените на имя вашего исполняемого файла для тестов
